import Header from "@/components/Header";
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="bg-fuchsia-800">
      <body className={inter.className}>
        <Header />
        <main className="p-8 bg-fuchsia-800">
          {children}
        </main>
      </body>
    </html>
  )
}
